### ISSUE TITLE
hangs with specific keyword

### ISSUE THREAD

**Issue by david0100101** [t3l3machus/psudohash#12]
Hi guys! I just tried to use it for the first time and it hanged, after some debugging it came down to this snippet: 

`
def mutations_handler(kword, trans_chars, total):
...
basic_mutations = unique(basic_mutations)
`

so basically here i got 3 million + entries in array and unique function does naive version of unique by simply repeatedly iterating through this array so we sort of getting quadratic complexity here, i have changed it to:

`
def mutations_handler(kword, trans_chars, total):
...
basic_mutations = set(basic_mutations) # unique(basic_mutations)
`  

and it seems to be working now, i guess set is much faster with some under the hood python magic, not sure if this change is required or i missed some arguments, i have used command as follows: `./psudohash.py -w elenamishina` , anyways thanks, have  a nice day !

**Comment by t3l3machus** [comment]
Hi @david0100101, thanks for the constructive suggestion, set is definitely better for sort-unique operations :)
