### ISSUE TITLE
Multithread suggestion

### ISSUE THREAD

**Issue by FLX-0x00** [t3l3machus/psudohash#5]
Hey, first of all, this tool is amazing. I wanted to ask if there is any way to add multithreading while generating the password candidates, as it seems to only use one core at a time.

Cheers!

**Comment by t3l3machus** [comment]
Hey, thanks a lot! It's tricky to program this tool in a multi-threaded fashion. In order for the output to include all combinations of character case AND leet substitution variations (as well as just char-case variations without leet), some of the pattern generation functions need to finish before others get to run. For example, if you run `./psudohash.py -w spacex -cpa`, for the results to include e.g., "sP4C3x!@#", which includes char-case, leet, and common padding values after, the char case generator needs to run first, then the leet substitution on the output of char-case variations, then the output of both as input in the common-paddings-after generator and so on. Hope this makes sense. I guess this could be programmed in a more efficient-threaded manner, but that would require a better brain than mine ¯\_(ツ)_/¯

**Comment by FLX-0x00** [comment]
hehe, nice thanks for the clarification. Seems like this might be a more complicated task than I thought.
